In [ ]:
import pandas as pd
import numpy as np
import kagglehub

# Download latest version
path = kagglehub.dataset_download("hassanjameelahmed/healthcare-analytics-patient-flow-data")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/hassanjameelahmed/healthcare-analytics-patient-flow-data/1.archive...

100%|██████████| 229k/229k [00:00<00:00, 51.2MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/hassanjameelahmed/healthcare-analytics-patient-flow-data/versions/1

In [ ]:
import os

os.listdir(path)

['healthcare_analytics_patient_flow_data.csv']

In [ ]:
df = pd.read_csv(path + '/healthcare_analytics_patient_flow_data.csv')

In [ ]:
df

,Patient Id,Patient Admission Date,Patient Admission Time,Merged,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
0,780-96-6113,9/9/2024,9:25:00 AM,W. Breede,Female,63,African American,NaN,Not Admission,5.0,32
1,714-35-6722,9/9/2024,4:42:00 PM,Y. Baldetti,Male,31,Asian,Orthopedics,Not Admission,NaN,22
2,571-85-3714,9/9/2024,12:14:00 AM,M. Semerad,Male,75,White,General Practice,Not Admission,NaN,16
3,404-43-9499,9/9/2024,8:33:00 PM,K. Blaydes,Male,79,African American,General Practice,Admission,NaN,38
4,552-51-5855,9/9/2024,7:25:00 PM,F. Dickerson,Female,24,African American,NaN,Admission,NaN,36
...,...,...,...,...,...,...,...,...,...,...,...
9211,353-25-3957,1/1/2024,11:01:00 PM,S. Levermore,Male,19,White,Cardiology,Not Admission,NaN,34
9212,608-47-0337,1/1/2024,5:25:00 PM,R. Boyle,Female,22,White,Orthopedics,Admission,NaN,45
9213,716-90-5923,1/1/2024,11:42:00 AM,V. Seadon,Female,8,African American,NaN,Admission,NaN,21
9214,641-52-3173,1/1/2024,4:59:00 AM,L. Harford,Female,37,White,NaN,Not Admission,5.0,10
9215,390-79-5650,1/1/2024,5:33:00 PM,E. Skerritt,Male,59,Asian,NaN,Not Admission,NaN,47

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient Id                  9216 non-null   object
 1   Patient Admission Date      9216 non-null   object
 2   Patient Admission Time      9216 non-null   object
 3   Merged                      9216 non-null   object
 4   Patient Gender              9216 non-null   object
 5   Patient Age                 9216 non-null   int64
 6   Patient Race                9216 non-null   object
 7   Department Referral         3816 non-null   object
 8   Patient Admission Flag      9216 non-null   object
 9   Patient Satisfaction Score  2517 non-null   float64
 10  Patient Waittime            9216 non-null   int64
dtypes: float64(1), int64(2), object(8)
memory usage: 792.1+ KB

In [ ]:
df.isna().sum()

Patient Id                       0
Patient Admission Date           0
Patient Admission Time           0
Merged                           0
Patient Gender                   0
Patient Age                      0
Patient Race                     0
Department Referral           5400
Patient Admission Flag           0
Patient Satisfaction Score    6699
Patient Waittime                 0
dtype: int64

In [ ]:
# Create boolean column — True if patient was referred by a department, False if they came on their own
df['has_referral'] = df['Department Referral'].notna()

In [ ]:
# Create boolean column — True if patient submitted a satisfaction score, False if they didn't
df['has_ Satisfaction'] = df['Patient Satisfaction Score'].notna()

In [ ]:
df

,Patient Id,Patient Admission Date,Patient Admission Time,Merged,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,has_referral,has_ Satisfaction
0,780-96-6113,9/9/2024,9:25:00 AM,W. Breede,Female,63,African American,NaN,Not Admission,5.0,32,False,True
1,714-35-6722,9/9/2024,4:42:00 PM,Y. Baldetti,Male,31,Asian,Orthopedics,Not Admission,NaN,22,True,False
2,571-85-3714,9/9/2024,12:14:00 AM,M. Semerad,Male,75,White,General Practice,Not Admission,NaN,16,True,False
3,404-43-9499,9/9/2024,8:33:00 PM,K. Blaydes,Male,79,African American,General Practice,Admission,NaN,38,True,False
4,552-51-5855,9/9/2024,7:25:00 PM,F. Dickerson,Female,24,African American,NaN,Admission,NaN,36,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9211,353-25-3957,1/1/2024,11:01:00 PM,S. Levermore,Male,19,White,Cardiology,Not Admission,NaN,34,True,False
9212,608-47-0337,1/1/2024,5:25:00 PM,R. Boyle,Female,22,White,Orthopedics,Admission,NaN,45,True,False
9213,716-90-5923,1/1/2024,11:42:00 AM,V. Seadon,Female,8,African American,NaN,Admission,NaN,21,False,False
9214,641-52-3173,1/1/2024,4:59:00 AM,L. Harford,Female,37,White,NaN,Not Admission,5.0,10,False,True
9215,390-79-5650,1/1/2024,5:33:00 PM,E. Skerritt,Male,59,Asian,NaN,Not Admission,NaN,47,False,False

In [ ]:
# Count patients by referral status — True: referred from a department, False: walked in alone
df['has_referral'].value_counts()

has_referral
False    5400
True     3816
Name: count, dtype: int64

In [ ]:
# Department that referred the most patients to the ER
df['Department Referral'].value_counts()

Department Referral
General Practice    1840
Orthopedics          995
Physiotherapy        276
Cardiology           248
Neurology            193
Gastroenterology     178
Renal                 86
Name: count, dtype: int64

In [ ]:
# Calculate average patient wait time in minutes
df['Patient Waittime'].mean()

np.float64(35.25987413194444)

In [ ]:
Patient_Referral_wait=df.groupby('Department Referral')['Patient Waittime'].mean()
Patient_Referral_wait

Department Referral
Cardiology          35.354839
Gastroenterology    35.831461
General Practice    34.912500
Neurology           36.803109
Orthopedics         34.982915
Physiotherapy       36.565217
Renal               34.697674
Name: Patient Waittime, dtype: float64

In [ ]:
Patient_Admission_flag_wait=df.groupby('Patient Admission Flag')['Patient Waittime'].mean()
Patient_Admission_flag_wait

Patient Admission Flag
Admission        34.967910
Not Admission    35.552346
Name: Patient Waittime, dtype: float64

In [ ]:
conditions = [
    df['Patient Age'] <= 18,
    df['Patient Age'] <= 35,
    df['Patient Age'] <=60 ,
    df['Patient Age'] >60
]

choices = ['Children', 'Young Adults', 'Adults', 'Seniors']

df['Age'] = np.select(conditions, choices, default='Seniors')

In [ ]:
df['Age'].value_counts()

Age
Adults          2923
Seniors         2198
Children        2110
Young Adults    1985
Name: count, dtype: int64

In [ ]:
df['Patient Gender'].value_counts()

Patient Gender
Male           4729
Female         4470
Femaleemale      17
Name: count, dtype: int64

In [ ]:
df['Patient Gender'] = df['Patient Gender'].replace('Femaleemale', 'Female')

In [ ]:
df['Patient Gender'].value_counts()

Patient Gender
Male      4729
Female    4487
Name: count, dtype: int64

In [ ]:
df['Patient Race'].value_counts()

Patient Race
White                            2571
African American                 1951
Two or More Races                1557
Asian                            1060
Declined to Identify             1030
Pacific Islander                  549
Native American/Alaska Native     498
Name: count, dtype: int64

In [ ]:
df['Patient Admission Time'].dtype

dtype('O')

In [ ]:
df['Patient Admission Date']=pd.to_datetime(df['Patient Admission Date'],dayfirst=True)

In [ ]:
df['Month']=df['Patient Admission Date'].dt.month
df['Month']

0       9
1       9
2       9
3       9
4       9
       ..
9211    1
9212    1
9213    1
9214    1
9215    1
Name: Month, Length: 9216, dtype: int32

In [ ]:
monthly_Patient =df.groupby('Month')['Patient Id'].count()
monthly_Patient

Month
1      513
2      431
3      506
4      948
5      999
6      991
7      952
8     1024
9      935
10     964
11     464
12     489
Name: Patient Id, dtype: int64

In [ ]:
monthly_Patient .idxmax()

np.int32(8)

In [ ]:
visit_counts=df['Patient Id'].value_counts()
returning = visit_counts[visit_counts > 1]
returning

Series([], Name: count, dtype: int64)

In [ ]:
df.to_csv('healthcare_analytics_patient_flow_data.csv', index=False)

In [ ]:
from google.colab import files
files.download('healthcare_analytics_patient_flow_data.csv')